on:
  pull_request:
    branches:
      - main
name: devtools_test

jobs:
  devtools_test:

    runs-on: ubuntu-18.04
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install Dependencies
        run: R -e 'install.packages("renv");renv::consent(provided=T);renv::restore()'

      - name: Run Tests
        run: R -e 'library(devtools);devtools::test(stop_on_failure=T, pkg=".");'
